# Generated by Django 5.1.3 on 2024-11-27 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_bookgenre_genre_post_delete_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.genre'),
        ),
    ]
